### PR TITLE
Fixes in upgrade to ver 3

### PR DESCRIPTION
**Pull request by nmpetkov**
As per commits:
- Fixing inproper pot file name
- Pot file update
- Proper old table names (pn_ prefix) in tables upgrade
- Proper handling empty dates

### CODE REVIEW

**Comment by craigh** [comment]
no, the prefix names cannot be added. the upgrade routine must rename the tables and remove the prefix. See other modules for examples or the core.

**Comment by nmpetkov** [comment]
Prefix in my case exist in old tables for this module only. To the moment worked with that prefix (old module from which I upgrading is 2.0.1). All is happening in Zikula 1.3.9.
I'm attempting now to manually rename the tables before running upgrade procedure.

**Comment by craigh** [comment]
as I said, the ***module*** is responsible to rename the table. [Like this in News](https://github.com/zikula-modules/News/blob/master/lib/News/Installer.php#L322) Manual rename should not be done

**Comment by nmpetkov** [comment]
Yes, I agree. Then in this module have to be added such a procedure.

**Comment by craigh** [comment]
that means this PR cannot be merged unless the table names are changed back

**Comment by nmpetkov** [comment]
In upgrade from 2.0.1 version and older, all files are with pn_ prefix, and it seems in one cases prefix to tables exist, in other cases not exist.
In my case exist, because this module is upgraded from old times (postnuke, Zikla 1.2)..

**Comment by nmpetkov** [comment]
I'l test further and will update this PR.

**Comment by nmpetkov** [comment]
All above to the moment makes upgrade to finish without errors.

But, then, polls are listed in admin panel, with following errors:
```
WARN (4): E_WARNING: Invalid argument supplied for foreach() in User.php line 163 
WARN (4): E_WARNING: Invalid argument supplied for foreach() in User.php line 163 
...
(number of errors corresponds nearly to number of polls.

For every error, in same page, the system displays information messages:
```
No poll found!
No poll found!
```
(That means - the poll is not found)

And many other errors then (in view votes in admin panel,  view poll in user interface).

In database all data is with different IDs, compared to tables before upgrade (this is because of implementing auto-increment columns in new format, I guess).

Some time I spent to determine reason for "not found" error and the warning, but no result for now.

I suggest somebody else also to attempt to upgrade from old version.

**Comment by nmpetkov** [comment]
One more note: module function as expected when testing in blank installation (without upgrade from old version).

**Comment by cmfcmf** [comment]
You can add the following lines to disable id autogeneration during the upgrade process, if that helps:
```php
$metadata = $this->entityManager->getClassMetaData('Entity_Class_Name');
$metadata->setIdGeneratorType(\Doctrine\ORM\Mapping\ClassMetadata::GENERATOR_TYPE_NONE);
```

**Comment by nmpetkov** [comment]
Interesting, will check :+1:

**Comment by nmpetkov** [comment]
This is ready to merge, I think.

**Comment by cmfcmf** [comment]
Looks good to me, what do you say @craigh?

**Pull request merged**
